services:
  hummingbot:
    container_name: hummingbot
    image: robotterlabs/hummingbot:latest
    entrypoint: ""
    # entrypoint: /bin/bash
    command: tail -f /dev/null
    # command: /root/.local/share/pnpm/pnpm start
    volumes:
      - ./volumes/client/conf:/root/hummingbot/conf
      - ./volumes/client/conf/connectors:/root/hummingbot/conf/connectors
      - ./volumes/client/conf/strategies:/root/hummingbot/conf/strategies
      - ./volumes/client/conf/controllers:/root/hummingbot/conf/controllers
      - ./volumes/client/conf/scripts:/root/hummingbot/conf/scripts
      - ./volumes/client/logs:/root/hummingbot/logs
      - ./volumes/client/data:/root/hummingbot/data
      - ./volumes/client/scripts:/root/hummingbot/scripts
      - ./volumes/client/controllers:/root/hummingbot/controllers
      - ./volumes/common/certs:/root/hummingbot/certs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
  gateway:
    container_name: gateway
    image: robotterlabs/gateway:latest
    entrypoint: ""
    # entrypoint: /bin/bash
    command: tail -f /dev/null
    # command: /root/.local/share/pnpm/pnpm start
    ports:
      - "15888:15888"
      - "8080:8080"
    volumes:
      - ./volumes/gateway/conf:/root/gateway/conf
      - ./volumes/gateway/logs:/root/gateway/logs
      - ./volumes/common/certs:/root/gateway/certs
    environment:
      - GATEWAY_PASSPHRASE=${GATEWAY_PASSPHRASE}
